### PR TITLE
Add internationalization

### LINKED ISSUE #42: Internationalization
This is going to be used by non-English speakers (ideally, at least). While we have a tiny amount of text let’s figure out what templating solution we’re going to use.

A cursory search led me to [vue-i18n](https://kazupon.github.io/vue-i18n/), but I am not wed to anything.

### PR DESCRIPTION
**Pull request by Sigafoos**
I went with vue-i18n, as it seemed like the best option. I'm fairly sure
I got everything, but we should probably move everything out of views
and into components (like with Home).

I have no idea how we're going to get translations for non-English
languages: we'll have to rely on PRs for that.

Closes #42

### CODE REVIEW

**Comment by Sigafoos** [comment]
Whoops, forgot to commit the package.json. I’m away from my laptop but will add that in a few minutes.

**Comment by Sigafoos** [comment]
I’d also like to add linting (why wait for #35?): https://eslint-plugin-vue-i18n.intlify.dev/started.html#installation

**Comment by Sigafoos** [comment]
The eslint config has support for something like `src/components/Home/locale.json`, which we don't use right now. I think I'd like to eventually, but it's out of the scope of this PR.

**Comment by mattgen88** [comment]
Needs conflicts resolved, but otherwise good to go

**Pull request merged**
